#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("buylist.Resource", IsApplication=true)]

namespace buylist
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int opaque_red = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int translucent_red = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int additem = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int budgetvalue = 2131230727;
			
			// aapt resource value: 0x7f080012
			public const int descripion1 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int descripion2 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int descripion3 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int descripion4 = 2131230741;
			
			// aapt resource value: 0x7f080005
			public const int existinglist = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int finallist = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int getbudget = 2131230723;
			
			// aapt resource value: 0x7f080016
			public const int gobutton = 2131230742;
			
			// aapt resource value: 0x7f080000
			public const int help_header = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int item_brief = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int item_cost = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int item_desc = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int item_priority = 2131230731;
			
			// aapt resource value: 0x7f080010
			public const int itemcheck = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int itemcost = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int mainheader = 2131230737;
			
			// aapt resource value: 0x7f08000d
			public const int savebtn = 2131230733;
			
			// aapt resource value: 0x7f080008
			public const int savebudget = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int textView1 = 2131230726;
			
			// aapt resource value: 0x7f08000e
			public const int textitem = 2131230734;
			
			// aapt resource value: 0x7f080004
			public const int whattobuy = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dpoutput = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int existinglistview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int inputdialogbox = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ItemInputForm = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int listview_row = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int description = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int first_line = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int fourth_line = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int gobtn = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int help = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int item_cost = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int item_name = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int save = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int second_line = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int third_line = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int welcometext = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
