#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("buylist.Resource", IsApplication=true)]

namespace buylist
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int descripion1 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int descripion2 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int descripion3 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int descripion4 = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int existinglist = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int gobutton = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int itemCost = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int item_brief = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int item_desc = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int mainheader = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int priority = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int savebtn = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int textitem = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int existinglistview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemInputForm = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int listview_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int description = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int first_line = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int fourth_line = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int gobtn = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int item_cost = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int item_name = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int save = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int second_line = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int third_line = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int welcometext = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
